### ISSUE TITLE
Provide tools to rescale trees

### ISSUE THREAD

**Issue by xrotwang** [phlorest/phlorest#14]
This could start out as 
- set of functions to be used with `newick.Node.visit` and
- a way to apply these to all trees in a Nexus file and
- possibly a command to run this on summary or posterior

**Comment by xrotwang** [comment]
@SimonGreenhill thought?

**Comment by SimonGreenhill** [comment]
Hmm.. Does this suggest that we should hook up `newick` into `python-nexus`, where it would fit neatly with commands like `deltree` etc?

**Comment by xrotwang** [comment]
Maybe. Since v2.x, `python-nexus` depends on `newick` anyway.

I've thought about where such functionality should go, too. But I think it's only really useful in the context of phlorest, where we know something about the scalings. And adding more tree-specific tools to `python-nexus` also feels a bit weird. And then `phyltr` has this:
https://github.com/lmaurits/phyltr/blob/master/src/phyltr/commands/scale.py

**Comment by SimonGreenhill** [comment]
hmm. ok, let's define the scope of the packages. I think it makes sense for newick to handle tree things (e.g. manipulations). Nexus and phyltr seem to be doing the same jobs in many places so aligning them (and not duplicating functionality) seems like a good idea but I'm not sure where the line is.

**Comment by xrotwang** [comment]
`phyltr` has a pretty clear philosophy of providing UNIX-style cli tools. So `python-nexus` could fill the "python API" niche. But I'm not sure how useful this is. So for the time being, I'd say we make functionality as phlorest-specific (and thus targeted) as possible. The fact that phlorest uses Nexus as container format for trees is somewhat accidental anyway.

**Comment by xrotwang** [comment]
Apart from the UI, I think the major difference between `phyltr` and `python-nexus` in terms of tree manipulation is that `phyltr` uses `ete3` for this and `python-nexus` uses `newick`. As long as `ete3` is somewhat difficult to install, I'd consider this an advantage of `python-nexus`. Now `phlorest` already uses `ete3` for some functionality, and nows how to get "raw" trees from Nexus files. So for most functionality `phlorest` won't need `phyltr` (for the tree unpacking) and won't need `ete3` functionality in `python-nexus`. (I guess I just wanted to convince myself even more of what I said above :) )

**Comment by xrotwang** [comment]
Looking at python-nexus once more, I think I'm going to add functionality to it which allows manipulating the newick strings of all trees in a file, by passing in a suitable callable. So the middle bullet point above will go into `python-nexus`.

**Comment by SimonGreenhill** [comment]
sounds good 👍
