### ISSUE TITLE
Change naming scheme from cldfbench_<x>.py

### ISSUE THREAD

**Issue by SimonGreenhill** [phlorest/phlorest#4]
I'm adding an unpublished dataset (under review), the current scheme requires something like

> cldfbench_greenhill_et_al_submitted.py

.. which is an extra thing to change and update when the paper is published (I realise that other things will need fixing but a file rename seems ... big). 

Can we get away with just cldfbench.py?

**Comment by SimonGreenhill** [comment]
riight is that because python needs a unique module name?

**Comment by xrotwang** [comment]
Not really. Unless we want to sacrifice the option to import multiple
datasets - and get cryptic errors, when we expect this to work.

Simon J Greenhill ***@***.***> schrieb am So., 21. Nov. 2021,
23:18:

**Comment by xrotwang** [comment]
Yes. Also, this practice is now used in many datasets already - not only
dplace.

Simon J Greenhill ***@***.***> schrieb am Mo., 22. Nov. 2021,
03:02:

**Comment by xrotwang** [comment]
I think that's the price we pay for making the dataset a python package. It
makes changing name-y thing difficult, because they propagate to various
places upon installing.

Robert Forkel ***@***.***> schrieb am Mo., 22. Nov. 2021,
07:07:

**Comment by SimonGreenhill** [comment]
One thought on this, should we have phlorest_xxx.py rather than cldfbench_xxx.py to avoid issues if I had a dataset and trees from xxx?

**Comment by xrotwang** [comment]
I think such a naming scheme might only put up an appearance of homogeneity which may not in fact be there. We already have lexibank datasets which **also** provide an additional StructureDataset (e.g. https://github.com/cldf-datasets/liljegrenhindukush), so I could well imagine a phlorest phylogeny coming with its own lexical data as Wordlist dataset. (And yes, I see us going down the slippery slope of multiple inheritance here ...)
