### ISSUE TITLE
investigate rescaling of trees.

### ISSUE THREAD

**Issue by SimonGreenhill** [phlorest/phlorest#5]
We have trees with branches in units of years, centuries, millennia, etc. Given that we are loading the trees during the cldfbench phase, can we use `python-newick` to rescale these to a consistent time frame (years) to avoid downstream issues.

**Comment by xrotwang** [comment]
That would be a simple `node.length * 100` or `*1000` for century or millenia, right?

**Comment by SimonGreenhill** [comment]
yeah or /1000 to convert millennia to years.

**Comment by xrotwang** [comment]
And you'd do this for **all** trees or just the summary? - Maybe we can start with the summary?

**Comment by SimonGreenhill** [comment]
I'd go for all (mixing and matching in one dataset seems like a recipe for issues), and convert to years. I'm happy to handle this if you want.

**Comment by xrotwang** [comment]
implemented now
