### ISSUE TITLE
call python nexus directly rather than shelling out?

### ISSUE THREAD

**Issue by SimonGreenhill** [phlorest/phlorest#6]
Lots of commands use `run_nexus` (https://github.com/cldf/phlorest/blob/main/src/phlorest/__init__.py#L262) to shell out to python-nexus. Should we just load the trees and handle them directly in python?

**Comment by xrotwang** [comment]
I thought about that. But then I thought the similarity to the "Makefile" might be useful/transparent as well. What convinced me to keep calling python-nexus' cli was that the nexus API isn't particularly convenient for this.

**Comment by SimonGreenhill** [comment]
hmm. Looking at the api here, or rather the lack of one, yes, I can see that this would be annoying. Suggests that I should refactor this at some point :/

**Comment by SimonGreenhill** [comment]
awesome, thanks -- that looks much clearer!
