### ISSUE TITLE
#NEXUS should be first statement

### ISSUE THREAD

**Issue by SimonGreenhill** [phlorest/phlorest#7]
The generated tree nexus files look like this:

```

#NEXUS 
...
```

Some phylogenetics programs fail when #NEXUS is not the very first line.

**Comment by SimonGreenhill** [comment]
I'm not sure if this is a bug in `python-nexus` or here.

**Comment by xrotwang** [comment]
Looks like a python-nexus problem. File template starts with a newline:
https://github.com/dlce-eva/python-nexus/blob/44cd8eeece1522b2839fbf4d586913ccdef7fbfc/src/nexus/writer.py#L8-L12

**Comment by xrotwang** [comment]
@SimonGreenhill Do you have an example for such a program - preferably one that I could install :) ?

**Comment by SimonGreenhill** [comment]
yep, [bayestraits](http://www.evolution.rdg.ac.uk/BayesTraitsV3.0.5/BayesTraitsV3.0.5.html) should fail with it.

**Comment by xrotwang** [comment]
hm. Just added a newline at the top of one of the example trees distributed with BayesTraits and it still worked. What error are you seeing?

**Comment by SimonGreenhill** [comment]
oh! awesome, I'm glad they fixed that! maybe this is an ancient bug that I've internalised. Still would be good to fix :)

**Comment by xrotwang** [comment]
fixed in python-nexus 2.3
